openapi: 3.0.3
info:
    title: House Listings Service
    description: Service for managing house listings
    version: 0.0.1
servers:
    - url: http://localhost:8000
paths:
    /:
        get:
            tags:
                - listings
            summary: list listings
            description: Retrieve a list of all listings
            operationId: listings#list
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Listing'
                                example:
                                    - address: Eius et ut illo commodi vitae qui.
                                      id: 7101026253662772559
                                      price: 3494167506848699601
                                      slug: Nihil consequuntur temporibus.
                                    - address: Eius et ut illo commodi vitae qui.
                                      id: 7101026253662772559
                                      price: 3494167506848699601
                                      slug: Nihil consequuntur temporibus.
                                    - address: Eius et ut illo commodi vitae qui.
                                      id: 7101026253662772559
                                      price: 3494167506848699601
                                      slug: Nihil consequuntur temporibus.
                                    - address: Eius et ut illo commodi vitae qui.
                                      id: 7101026253662772559
                                      price: 3494167506848699601
                                      slug: Nihil consequuntur temporibus.
                            example:
                                - address: Eius et ut illo commodi vitae qui.
                                  id: 7101026253662772559
                                  price: 3494167506848699601
                                  slug: Nihil consequuntur temporibus.
                                - address: Eius et ut illo commodi vitae qui.
                                  id: 7101026253662772559
                                  price: 3494167506848699601
                                  slug: Nihil consequuntur temporibus.
                "404":
                    description: 'not_found: Listing not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'internal_error: Internal server error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - listings
            summary: add listings
            description: Create a listing
            operationId: listings#add
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Listing'
                        example:
                            address: Quo eius impedit.
                            id: 1475321351850767455
                            price: 2997242765460517709
                            slug: Exercitationem sed omnis maxime.
            responses:
                "201":
                    description: Created response.
                "404":
                    description: 'not_found: Listing not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'internal_error: Internal server error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /{slug}:
        delete:
            tags:
                - listings
            summary: delete listings
            description: Delete a listing
            operationId: listings#delete
            parameters:
                - name: slug
                  in: path
                  description: Unique identifier of the listing
                  required: true
                  schema:
                    type: string
                    description: Unique identifier of the listing
                    example: Laborum repudiandae voluptas ullam unde vel.
                  example: Quo deleniti.
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: 'not_found: Listing not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'internal_error: Internal server error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        get:
            tags:
                - listings
            summary: get listings
            description: Retrieve a single listing
            operationId: listings#get
            parameters:
                - name: slug
                  in: path
                  description: Unique identifier of the listing
                  required: true
                  schema:
                    type: string
                    description: Unique identifier of the listing
                    example: Quo suscipit eligendi qui.
                  example: Sint voluptas sit deserunt.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Listing'
                            example:
                                address: A ducimus.
                                id: 8284575409095266097
                                price: 8843690428386137881
                                slug: Soluta saepe aspernatur.
                "404":
                    description: 'not_found: Listing not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'internal_error: Internal server error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        put:
            tags:
                - listings
            summary: update listings
            description: Update a listing
            operationId: listings#update
            parameters:
                - name: slug
                  in: path
                  description: Unique identifier of the listing
                  required: true
                  schema:
                    type: string
                    description: Unique identifier of the listing
                    example: Quia rem omnis error maxime.
                  example: Ab modi id occaecati in.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateRequestBody'
                        example:
                            listing:
                                address: Sed laudantium voluptate totam ea.
                                id: 2796687764175130019
                                price: 1129553093244879647
                                slug: Harum beatae provident totam voluptatem.
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: 'not_found: Listing not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'internal_error: Internal server error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            description: Listing not found
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        Listing:
            type: object
            properties:
                address:
                    type: string
                    description: Address of the house
                    example: Velit voluptates illo dicta.
                id:
                    type: integer
                    description: Unique identifier of the listing
                    example: 5427408462330035481
                    format: int64
                price:
                    type: integer
                    description: Price of the house
                    example: 3968952534661874874
                    format: int64
                slug:
                    type: string
                    description: Unique identifier of the listing
                    example: Ut consequuntur ut illum nesciunt quis.
            description: A Listing describes a house available for sale
            example:
                address: Nostrum exercitationem incidunt aut officiis.
                id: 1198539938166453767
                price: 1638998349999074196
                slug: Voluptatem illo atque aspernatur.
            required:
                - slug
                - address
                - price
        UpdateRequestBody:
            type: object
            properties:
                listing:
                    $ref: '#/components/schemas/Listing'
            example:
                listing:
                    address: Sed laudantium voluptate totam ea.
                    id: 2796687764175130019
                    price: 1129553093244879647
                    slug: Harum beatae provident totam voluptatem.
            required:
                - listing
tags:
    - name: listings
      description: The listings service provides operations on managing house listings.
